# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_keyword', models.CharField(max_length=255)),
                ('search_user', models.CharField(default='Unknown', max_length=100)),
                ('search_time', models.DateTimeField()),
                ('search_first', models.CharField(max_length=50)),
                ('search_second', models.CharField(default=None, max_length=50)),
                ('search_third', models.CharField(default=None, max_length=50)),
                ('search_fourth', models.CharField(default=None, max_length=50)),
                ('search_fifth', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
