# Generated by Django 2.0.1 on 2018-01-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180116_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='search_fifth',
        ),
        migrations.RemoveField(
            model_name='history',
            name='search_first',
        ),
        migrations.RemoveField(
            model_name='history',
            name='search_fourth',
        ),
        migrations.RemoveField(
            model_name='history',
            name='search_second',
        ),
        migrations.RemoveField(
            model_name='history',
            name='search_third',
        ),
        migrations.AddField(
            model_name='history',
            name='search_imagelist',
            field=models.CharField(default='Error', max_length=255),
        ),
        migrations.AddField(
            model_name='history',
            name='search_linklist',
            field=models.CharField(default='Error', max_length=255),
        ),
        migrations.AddField(
            model_name='history',
            name='search_namelist',
            field=models.CharField(default='Error', max_length=255),
        ),
        migrations.AddField(
            model_name='history',
            name='search_pricelist',
            field=models.CharField(default='Error', max_length=255),
        ),
        migrations.AddField(
            model_name='history',
            name='search_shoplist',
            field=models.CharField(default='Error', max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='search_user',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
