# Generated by Django 2.0.1 on 2018-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180117_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('first_shop', models.TextField(default='없음', max_length=255)),
                ('count', models.IntegerField(default=0, max_length=255)),
            ],
        ),
    ]
